AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CollAction backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        BUCKET: !Ref ProfilePictureUploadBucket
        LOCAL_RESOURCES_ONLY: !Ref LocalResourcesOnly

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  LocalResourcesOnly:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  FirebaseProjectId:
    Type: String

Resources:

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          FirebaseAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - !Ref FirebaseProjectId
              issuer: !Sub https://securetoken.google.com/${FirebaseProjectId}
        DefaultAuthorizer: FirebaseAuthorizer
      StageName: !Ref Stage
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowOrigins:
          - http://localhost:8080
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"

  ProfilePictureUploadBucket:
    Type: 'AWS::S3::Bucket'

  ProfilePictureBucket:
    Type: 'AWS::S3::Bucket'

  GetPictureUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getpictureuploadurl/
      Handler: getpictureuploadurl
      Runtime: go1.x
      Policies:
        - S3CrudPolicy:
            BucketName:
              !Ref ProfilePictureUploadBucket
      Events:
        ProfilePictureUpload:
          Type: HttpApi
          Properties:
            Path: /upload-profile-picture
            Method: get
            ApiId: !Ref HttpApi

  ProcessProfilePictureFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: process-profile-picture/
      Handler: process-profile-picture
      Runtime: go1.x
      Environment:
        Variables:
          # Beware of recursive execution! Double check referenced buckets!
          OUTPUT_BUCKET_NAME: !Ref ProfilePictureBucket
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - s3:GetObject*
              - s3:PutObject*
              - s3:DeleteObject*
            Resource: '*'
        - S3CrudPolicy:
            BucketName:
              !Ref ProfilePictureBucket
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProfilePictureUploadBucket
            Events: s3:ObjectCreated:*

  WhoamiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: whoami/
      Handler: whoami
      Runtime: go1.x
      Events:
        Whoami:
          Type: HttpApi
          Properties:
            Path: /whoami
            Method: get
            ApiId: !Ref HttpApi

  # EmailContactFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: email_contact/
  #     Handler: app.lambda_handler
  #     Runtime: python3.7
  #     Events:
  #       Contact:
  #         Type: HttpApi
  #         Properties:
  #           Path: /contact
  #           Method: post
  #           ApiId: !Ref HttpApi
  #           Policies:
  #             - Statement:
  #               - Sid: SSMGetParameterPolicy
  #                 Effect: Allow
  #                 Action:
  #                 - ssm:GetParameter
  #                 Resource: '*'
  #             - Statement:
  #               - Sid: AuthorizeFromAddress
  #                 Effect: Allow
  #                 Action:
  #                 - ses:SendEmail
  #                 Resource: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HttpApiHelloWorld:
    Description: "API Gateway endpoint URL for deployed stage for Hello World function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello"
