AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CollAction backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        LOCAL_RESOURCES_ONLY: !Ref LocalResourcesOnly

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  LocalResourcesOnly:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  FirebaseProjectId:
    Type: String

Resources:

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          FirebaseAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - !Ref FirebaseProjectId
              issuer: !Sub https://securetoken.google.com/${FirebaseProjectId}
        DefaultAuthorizer: FirebaseAuthorizer
      StageName: !Ref Stage
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowOrigins:
          - http://localhost:8080
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: "NONE"

  ProfilePictureUploadBucket:
    Type: 'AWS::S3::Bucket'

  StaticHostingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: '404'
              KeyPrefixEquals: profile-pictures/
            RedirectRule:
              ReplaceKeyWith: profile-pictures/anonymous.png

  UploadProfilePictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: upload-profile-picture/
      Handler: upload-profile-picture
      Runtime: go1.x
      Environment:
        Variables:
          BUCKET: !Ref ProfilePictureUploadBucket
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - s3:PutObject*
            Resource: '*'
      Events:
        ProfilePictureUpload:
          Type: HttpApi
          Properties:
            Path: /upload-profile-picture
            Method: get
            ApiId: !Ref HttpApi

  ProcessProfilePictureFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: process-profile-picture/
      Handler: process-profile-picture
      Runtime: go1.x
      Environment:
        Variables:
          # Beware of recursive execution! Double check referenced buckets!
          OUTPUT_BUCKET_NAME: !Ref StaticHostingBucket
          KEY_PREIFX: profile-pictures/
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - s3:GetObject*
              - s3:PutObject*
              - s3:DeleteObject*
              - rekognition:DetectModerationLabels
            Resource: '*'
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ProfilePictureUploadBucket
            Events: s3:ObjectCreated:*

  WhoamiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: whoami/
      Handler: whoami
      Runtime: go1.x
      Events:
        Whoami:
          Type: HttpApi
          Properties:
            Path: /whoami
            Method: get
            ApiId: !Ref HttpApi

  ParticipationStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  AggregateParticipationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: participation/aggregator
      Handler: aggregator
      Runtime: go1.x
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt ParticipationStream.Arn
            BatchSize: 100
            StartingPosition: LATEST

  ParticipationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: "userID"
          AttributeType: "S"
        - AttributeName: "crowdactionID"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "N"
      KeySchema:
            - AttributeName: "userID"
              KeyType: "HASH"
            - AttributeName: "crowdactionID"
              KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "participantCrowdactions"
          KeySchema:
          - AttributeName: "userID"
            KeyType: "HASH"
          - AttributeName: "timestamp"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "crowdactionID"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: "crowdactionParticipants"
          KeySchema:
            - AttributeName: "crowdactionID"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "userID"
              - "name"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  ParticipationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: participation/api
      Handler: api
      Runtime: go1.x
      Environment:
        Variables:
          PARTICIPATION_TABLE: !Ref ParticipationTable
          PARTICIPATION_STREAM: !Ref ParticipationStream
      Events:
        ChangeParticipation:
          Type: HttpApi
          Properties:
            Path: /crowdactions/{crowdactionID}/participation
            Method: any
            ApiId: !Ref HttpApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref ParticipationTable
        - Statement:
          - Sid: ParticipationStreamPutRecordPolicy
            Effect: Allow
            Action:
            - kinesis:PutRecord
            Resource: '*'


  # EmailContactFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: email_contact/
  #     Handler: app.lambda_handler
  #     Runtime: python3.7
  #     Events:
  #       Contact:
  #         Type: HttpApi
  #         Properties:
  #           Path: /contact
  #           Method: post
  #           ApiId: !Ref HttpApi
  #           Policies:
  #             - Statement:
  #               - Sid: SSMGetParameterPolicy
  #                 Effect: Allow
  #                 Action:
  #                 - ssm:GetParameter
  #                 Resource: '*'
  #             - Statement:
  #               - Sid: AuthorizeFromAddress
  #                 Effect: Allow
  #                 Action:
  #                 - ses:SendEmail
  #                 Resource: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HttpApiHelloWorld:
    Description: "API Gateway endpoint URL for deployed stage for Hello World function"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello"
