# ==================================================
# This is the main worflow for testing, building and
# deploying the app.
#   The following is not yet implemented:
#    - Deploying to prod (run on master, config for prod)
# ==================================================

name: CICD

on:
  push:
    branches: [development]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build
        run: |
          sam build
          echo ${{ secrets.AWS_SAMCONFIG_DEV }} | base64 -d > samconfig.toml
      - name: Cache build (store)
        uses: actions/cache@v2
        with:
          path: ./.aws-sam
          key: cache-sam-build-${{ github.sha }}
      
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v2
      - name: Cache build (load)
        uses: actions/cache@v2
        with:
          path: ./.aws-sam
          key: cache-sam-build-${{ github.sha }}
      - name: Set up GoLang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Run unit tests
        run: go test ./...

  deploy: # Dynamically deploys to dev or prod depending on the branch
    if: ${{ github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code from repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Cache build (load)
        uses: actions/cache@v2
        with:
          path: ./.aws-sam
          key: cache-sam-build-${{ github.sha }}
      - name: Deploy
        run: |
          echo ${{ github.ref == 'refs/heads/master' && secrets.AWS_SAMCONFIG_PROD || secrets.AWS_SAMCONFIG_DEV }} | \
            base64 -d > samconfig.toml
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-progressbar \
            --stack-name collaction-${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }} \
            --tags \
                ci_cd:run_number=${{ github.run_number }} \
                git:sha=${{ github.sha }}
